### PR TITLE
JBIDE-22446 use central.tpc.version = 4.60.0.Final-SNAPSHOT

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-22446 use central.tpc.version = 4.60.0.Final-SNAPSHOT -- should have made this change 4 sprints ago!

### CODE REVIEW

**Comment by alexeykazakov** [comment]
As you can see in the PR check above this PR doesn't solve the problem:
[ERROR] Found property angularjs.repo.url = http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/4.60.0.Final-SNAPSHOT/REPO/

It's Final, not Alpha now but it's still a snapshot.

**Comment by nickboldt** [comment]
Re run the PR check using the latest parent pom and it should now work.

**Comment by alexeykazakov** [comment]
Still failing.

**Comment by psrna** [comment]
testPR

**Comment by nickboldt** [comment]
PR works when I run it locally. *shrug*

**Comment by psrna** [comment]
I've configured pr check job which runs JST Integration Tests.

**Comment by alexeykazakov** [comment]
What is CDI11-Integration-tests check about?

**Comment by nickboldt** [comment]
Here are the tests run for CDI11-integration:

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jst.prcheck/jdk=jdk1.8,label=rhel7/lastSuccessfulBuild/artifact/jbosstools-integration-tests/tests/org.jboss.tools.jst.ui.bot.test/target/surefire-reports/org.jboss.tools.jst.ui.bot.test.AllJSTTests.txt

**Comment by alexeykazakov** [comment]
CDI11-Integration-tests is a weird name for JST tests ;)

**Comment by nickboldt** [comment]
Yes. Curiously, the link for Details on "JST-Integration-tests" goes to the same job.

**Comment by nickboldt** [comment]
Opened a new PR #568 but it still has the CDI11-Integration-tests notation there too. Not sure how to get rid of that for future PRs, since the jst.prcheck job now only has the "JST-Integration-tests" context.

**Pull request closed without merging**
