### PR TITLE
[JBIDE-26256] - NPE while closing JBoss Tools HTML Editor editor tab in IDE

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@odockal @mmalina dare to test it as it seems also platform related

**Comment by mmalina** [comment]
@jeffmaury I tried, but unfortunately I'm stuck. First I tried with Eclipse + JBT, but I can't reproduce the original issue there (but several of us saw it in devstudio). But in devstudio standalone I can't install the newly build feature because it would collide with the product-defined features. Then I tried Eclipse + devstudio BYOE, but I can't reproduce there either.

**Comment by mmalina** [comment]
@odockal did you have any luck with this?

**Comment by odockal** [comment]
@jeffmaury @mmalina I have tested two cases, in both cases I have run cdk itests that executes IDE from within devstudio. In first case, I did not imported jst project and I managed to reproduce npe error, visible in error log. In second case, I have imported jst repo with jeff's bug fix and run the tests again, here I did not get any errors while closing (x)html in editor. I consider this changes removing npe bug.

**Pull request merged**
