### PR TITLE
Fixes #610 - add 4.0 and 5.0 servlets to dropdown

### LINKED ISSUE #610: There have been 2 new web facets since last updated
Most combos only list up to web 3.1.  They are missing web / servlet  4.0 and 5.0.

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
LGTM but asking @sbouchet about JST lifecycle

**Review by sbouchet — APPROVED** [review]
LGTM. JST isn't deprecated nor removed from JBossTools for now.

**Comment by robstryker** [comment]
Just so the issue doesn't get lost, who should merge it?  @jeffmaury @sbouchet ?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
