### PR TITLE
JBIDE-22669 SelectionBar returns incorrect visibility

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@scabanovich could you please review this PR?

**Comment by scabanovich** [comment]
Maybe it is more safe to override isVisible() as

	@Override
	public boolean isVisible() {
		return isBarVisible && super.isVisible();
	}

It seems that setVisible(boolean) intentionally does not call super method, it rather switches realBar/emptyBar.

**Comment by scabanovich** [comment]
On the second thought, what is done in setVisible(boolean) should be done in another method (like setRealBarVisible(boolean) ) that does not change super behavior, then all calls to selectionBar.setVisible from VpeEditorPart, VpvEditorPart, JSPMultiPageEditorPart, SelectionBarHandler should be replaced by selectionBar.setRealBarVisible.

At least, if we do not want to change the logic of selection bar. Overriding either setVisible in another way then it is now or isVisible as I suggested before may change that logic.

**Comment by rawagner** [comment]
@scabanovich you're right. I've added setRealBarVisible method and replaced all setVisible calls. See also https://github.com/jbosstools/jbosstools-vpe/pull/334

**Comment by scabanovich** [comment]
Looks good to me.

**Comment by alexeykazakov** [comment]
testPR

**Pull request merged**
