### PR TITLE
JBDS-3263 Vpe pages initialization enhancement

### PR DESCRIPTION
**Pull request by kmarmaliykov**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Any jira for this task?

**Comment by kmarmaliykov** [comment]
No, I create this PR as a part of removing VPE. Anyway, it will not corrupt
anything even if VPE will not be removed in JBDS9, but will be needed for
showing only source tab for Mac OS(see
https://issues.jboss.org/browse/JBDS-3263)

**Comment by alexeykazakov** [comment]
Then please add JBDS-3263 to the beginning of the commit's message.

**Comment by kmarmaliykov** [comment]
I update commit message and link this PR to jira

**Pull request merged**
