### PR TITLE
jbide-22994: Remove old Help->Report Problem dialog

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@bdshadow ok, now JST integration tests failed :(

**Comment by bdshadow** [comment]
testPR

**Comment by alexeykazakov** [comment]
testPR

**Comment by bdshadow** [comment]
It's magic. Just 2 additional PR tests fixed everything.

**Comment by alexeykazakov** [comment]
Still no response from QE. I can't wait any longer bc this PR fixes our build. Merging.

**Pull request merged**
