### PR TITLE
JBIDE-24046 Move jst.itests from jbosstools-integration-tests to jbosstools-jst

### PR DESCRIPTION
**Pull request by psrna**

### CODE REVIEW

**Comment by psrna** [comment]
testPR

**Comment by psrna** [comment]
testPR

**Comment by psrna** [comment]
testPR

**Comment by psrna** [comment]
testPR

**Comment by psrna** [comment]
@jeffmaury can you please review and merge?

If you want to try out itests from command line please use **`mvn clean verify -PITests -Pdownload-devstudio`**

You also need bower on your path.
`npm install -g bower`

Thx!

**Comment by zcervink** [comment]
@psrna @odockal the https://issues.redhat.com/browse/JBIDE-24046 issue has been resolved as 'Out of Date', what about to close this PR?

**Comment by zcervink** [comment]
@odockal Jira JBIDE-24046 is close as out of date - please close this PR sice you are the Assignee to the jira (so I can close the jira or close it by yourself), thank you

**Comment by odockal** [comment]
@psrna Sorry Palo...

**Pull request closed without merging**
