### PR TITLE
JBIDE-19795: Adding Wizard for "Bower Init" functionality

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
No new tests for the wizard? :)

**Comment by ibuziuk** [comment]
@alexeykazakov would add some later next week ;-)

**Comment by alexeykazakov** [comment]
OK. I will merge it w/o tests since the Beta2 code freeze is approaching soon. But please don't forget to add tests for CR1 ;)

**Comment by ibuziuk** [comment]
I would probably add them in Beta2 (at least that's the plan ;-))

**Pull request merged**
