### PR TITLE
JBIDE-21001 do we even need the eclipse-angul......arjs repo here? builds & tests all pass locally

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Yes, we need angularJs here to have it available for tests. Rejecting.

**Comment by nickboldt** [comment]
But I ran all the tests after making the above change and they all passed. Are you sure you actually need it? There's nothing in the features or manifests which even reference angular.

**Comment by alexeykazakov** [comment]
Then we need to start using it in the test. I will take a look tomorrow. Anyway, thank you for pointing at the problem.

**Comment by nickboldt** [comment]
The bigger problem is that we have 2 versions of AngularJS defined in two places, and only ONE was updated to use 1.0. I left comments in that pom SPECIFICALLY so that people might remember that updates need to happen in TWO repos, but of course no one reads comments even when they're right next to the edits they're making. :(

**Pull request closed without merging**
