### PR TITLE
JBIDE-19795: SWTBot test for "Bower Init" wizard. Clean up. Minor Refactoring

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
The new test hangs on my Ubuntu. I see New->Other... dialog is opened but nothing happens after that.

**Comment by ibuziuk** [comment]
@alexeykazakov weird. I have build everything before creating PR and the build was successful

**Comment by alexeykazakov** [comment]
Not working for Denis either (Ubuntu).

**Comment by ibuziuk** [comment]
@alexeykazakov @dgolovin test is running just fine via Run As -> SWT Bot test. However, when I do it via maven I faced the same issue. Basic tests from samples also hangs on maven. Any Ideas?

**Comment by ibuziuk** [comment]
@dgolovin I have updated PR and disable this test. I guess if we won't be able to make it work for maven we can leave it as-is and figure out how to fix it later

**Pull request merged**
